name: mri_tools_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - polars
  - python-kaleido
  - scipy
  - numpy
  - plotly
  - simple-parsing
  - tqdm
  - nibabel
  - wandb
  - pytest
  - rich